version: '2'

services:
  blog:
    build:
      context: .
      dockerfile: springboot.dockerfile
    depends_on:
    - postgres
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    ports:
    - "8080:8080"
    networks:
    - app-network
  postgres:
    image: postgres:11.0
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=postgres
    ports:
    - "5432:5432"
    volumes:
    - postgres_volume:/var/lib/postgresql/data
    networks:
    - app-network

volumes:
  postgres_volume:

networks:
  app-network:
    driver: bridge
